---
title: "Network_Revision"
format: html
editor: visual
---

## JDS Network Revisions

```{r}

library(dplyr)
library(ggplot2)
library(forcats)
library(tidyr)
library(ggthemes)
library(scales)
library(RMySQL)
library(DBI)

Sys.setenv(DB_USERNAME = , DB_PASSWORD = )
setwd("C:/Users/shrivastava_r/OneDrive - Westat/Desktop/OSS_Directory/OSS_Federal_Gov_Codegov/Analysis/01_EDA")
```

```{r}
degree_net <- read.csv("C:/Users/shrivastava_r/OneDrive - Westat/Desktop/OSS_Directory/OSS_Federal_Gov_Codegov/Analysis/01_EDA/degree_centrality.csv", header = TRUE)
```

```{r}
degree_net <- degree_net |>
    mutate(agency = case_when(
  agency == "Department Of Defence" ~ "Department of Defense",
  agency == "Department Of Energy" ~ "Department of Energy",
  agency == "Department Of Homeland Security" ~ "Department of Homeland Security",
  agency == "Department Of Justice" ~ "Department of Justice",
  agency == "Department Of Labor" ~ "Department of Labor",
  agency == "Department Of Education" ~ "Department of Education",
  agency == "Federal Election Commision" ~ "Federal Election Commission",
  agency == "Environmental Protection Agency" ~ "Environmental Protection Agency",
  agency == "General Services Administration" ~ "General Services Administration",
  agency == "Department Of Health And Human Services" ~ "Department of Health & Human Services",
  agency == "International" ~ "Agency for International Development",
  agency == "National Aeronautics And Space Administration" ~ "National Aeronautics and Space Administration",
  agency == "National Science Foundation" ~ "National Science Foundation",
  agency == "Social Security Administration" ~ "Social Security Administration",
  agency == "Small Business Administration" ~ "Small Business Administration",
  agency == "Department Of Transportation" ~ "Department of Transportation",
  agency == "Department Of The Treasury" ~ "Department of the Treasury",
  agency == "Department Of Agriculture" ~ "Department of Agriculture",
  agency == "Veterans Affairs" ~ "Veterans Affairs"
))


```

```{r}


`%!in%` = Negate(`%in%`)

degree_net <- degree_net |>
  filter(agency %!in% c("National Science Foundation", "Social Security Administration", "Small Business Administration", "Department of Justice", "Department of Education", "Department of the Treasury","Federal Election Commission", "Environmental Protection Agency", "Veterans Affairs"))


degree_net %>%
  mutate(agency = fct_reorder(agency, degree_centrality, .fun='median')) %>%
  ggplot( aes(x=reorder(agency, degree_centrality), y=degree_centrality)) + 
    geom_boxplot() +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  theme_economist() +
  coord_flip() +
  annotation_logticks(sides = 'lr') +
  labs(title = "Degree Centrality of Nodes in Contributor Network",
        x = element_blank(),
        y = "Degree Centrality") +
  theme(plot.title = element_text(hjust = 3.5, 
                                face = "bold", 
                                size = 12),
          plot.margin = margin(.2, .2, .2, .2, "cm"),
          legend.title = element_blank(),
          legend.position = "bottom")
  theme(panel.grid.minor = element_blank())
  
ggsave("Revised_11_degree_centrality_box.emf", width = 7, height = 4, units = "in")
ggsave("Revised_11_degree_centrality_box.pdf", width = 7, height = 4, units = "in")
```

```{r}

between_net <- read.csv("C:/Users/shrivastava_r/OneDrive - Westat/Desktop/OSS_Directory/OSS_Federal_Gov_Codegov/Analysis/01_EDA/betweenness_centrality.csv", header = TRUE)

```

```{r}

between_net <- between_net |>
    mutate(agency = case_when(
  agency == "Department Of Defence" ~ "Department of Defense",
  agency == "Department Of Energy" ~ "Department of Energy",
  agency == "Department Of Homeland Security" ~ "Department of Homeland Security",
  agency == "Department Of Justice" ~ "Department of Justice",
  agency == "Department Of Labor" ~ "Department of Labor",
  agency == "Department Of Education" ~ "Department of Education",
  agency == "Federal Election Commision" ~ "Federal Election Commission",
  agency == "Environmental Protection Agency" ~ "Environmental Protection Agency",
  agency == "General Services Administration" ~ "General Services Administration",
  agency == "Department Of Health And Human Services" ~ "Department of Health & Human Services",
  agency == "International" ~ "Agency for International Development",
  agency == "National Aeronautics And Space Administration" ~ "National Aeronautics and Space Administration",
  agency == "National Science Foundation" ~ "National Science Foundation",
  agency == "Social Security Administration" ~ "Social Security Administration",
  agency == "Small Business Administration" ~ "Small Business Administration",
  agency == "Department Of Transportation" ~ "Department of Transportation",
  agency == "Department Of The Treasury" ~ "Department of the Treasury",
  agency == "Department Of Agriculture" ~ "Department of Agriculture",
  agency == "Veterans Affairs" ~ "Veterans Affairs"
))


```

```{r}

`%!in%` = Negate(`%in%`)

between_net <- between_net |>
  filter(agency %!in% c("National Science Foundation", "Social Security Administration", "Small Business Administration", "Department of Justice", "Department of Education", "Department of the Treasury","Federal Election Commision", "Environmental Protection Agency", "Veterans Affairs"))


between_net %>%
  mutate(agency = fct_reorder(agency, betweenness_centrality, .fun='median')) %>%
  ggplot( aes(x=reorder(agency, betweenness_centrality), y=betweenness_centrality)) + 
    geom_boxplot() +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  theme_economist() +
  coord_flip() +
  annotation_logticks(sides = 'lr') +
  labs(title = "Betweenness Centrality of Nodes in Contributor Network",
        x = element_blank(),
        y = "Betweenness Centrality") +
  theme(plot.title = element_text(hjust = 2.5, 
                                face = "bold", 
                                size = 12),
          plot.margin = margin(.2, .2, .2, .2, "cm"),
          legend.title = element_blank(),
          legend.position = "bottom")
  theme(panel.grid.minor = element_blank())
  
ggsave("Revised_12_between_centrality_box.emf", width = 7, height = 4, units = "in")
ggsave("Revised_12_between_centrality_box.pdf", width = 7, height = 4, units = "in")
```

### KLOC

```{r}
# establishing connection and listing all tables in database
con <- dbConnect(MySQL(), user = Sys.getenv("DB_USERNAME"), password = Sys.getenv("DB_PASSWORD"),
    dbname = "codegov", host = "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com")

agency_year_code <- dbReadTable(con, "codegov_gh_commits_by_year_agency")

dbDisconnect(con)
```

```{r}
check_kloc_2009_2021 <- agency_year_code|>
    #filter(year %in% 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021) |>
  mutate(agency = case_when(
  agency == "DOD" ~ "Department of Defense",
  agency == "Department of Energy" ~ "Department of Energy",
  agency == "Department of Homeland Security" ~ "Department of Homeland Security",
  agency == "Department of Justice" ~ "Department of Justice",
  agency == "Department of Labor" ~ "Department of Labor",
  agency == "Education" ~ "Department of Education",
  agency == "Election" ~ "Federal Election Commision",
  agency == "Environmental Protection Agency" ~ "Environmental Protection Agency",
  agency == "GSA" ~ "General Services Administration",
  agency == "HHS" ~ "Department of Health & Human Services",
  agency == "International" ~ "Agency for International Development",
  agency == "NASA" ~ "National Aeronautics and Space Administration",
  agency == "NSF" ~ "National Science Foundation",
  agency == "SSA" ~ "Social Security Administration",
  agency == "Small Business" ~ "Small Business Administration",
  agency == "Transportation" ~ "Department of Transportation",
  agency == "Treasury" ~ "Department of the Treasury",
  agency == "USDA" ~ "Department of Agriculture",
  agency == "Veteran" ~ "Veterans Affairs"
)) |>
  filter(year > 2008 & year < 2022) |>
  group_by(agency) |>
  summarise(kloc = sum(additions)/1000)

write.csv(check_kloc_2009_2021, "Agency_Total_KLOC.csv")


```

```{r}
total_kloc <- agency_year_code|>
  group_by(agency) |>
  filter(agency =='Department of Energy') |>
  filter(year == 2007) |>
  summarise(kloc = sum(additions)/1000)

```

```{r}

total_kloc |>
  summarise(kloc_tot = sum(additions))

```

```{r}

year_projects <- agency_year_code|>
  group_by(year) |>
  summarise(projects = n(),
            lines = sum(additions))

```

### Project Impact Metrics

```{r}

# establishing connection and listing all tables in database
con <- dbConnect(MySQL(), user = Sys.getenv("DB_USERNAME"), password = Sys.getenv("DB_PASSWORD"),
    dbname = "codegov", host = "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com")

repos_table <- dbReadTable(con, "codegov_gh_data_repos")

dbDisconnect(con)

```

```{r}

# establishing connection and listing all tables in database
con <- dbConnect(MySQL(), user = Sys.getenv("DB_USERNAME"), password = Sys.getenv("DB_PASSWORD"),
    dbname = "codegov", host = "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com")

agency_slugs <- dbReadTable(con, "codegov_slugs")

dbDisconnect(con)


```

```{r}
final_repos <- repos_table

final_repos$agency <- agency_slugs$agency
final_repos$slug <- agency_slugs$slug
```

```{r}
final_repos <- final_repos |>
  select(agency, fork_count, stargazer_count, pull_requests_count) |>
  mutate(agency = case_when(
  agency == "DOD" ~ "Department of Defense",
  agency == "Department of Energy" ~ "Department of Energy",
  agency == "Department of Homeland Security" ~ "Department of Homeland Security",
  agency == "Department of Justice" ~ "Department of Justice",
  agency == "Department of Labor" ~ "Department of Labor",
  agency == "Education" ~ "Department of Education",
  agency == "Election" ~ "Federal Election Commission",
  agency == "Environmental Protection Agency" ~ "Environmental Protection Agency",
  agency == "GSA" ~ "General Services Administration",
  agency == "HHS" ~ "Department of Health & Human Services",
  agency == "International" ~ "Agency for International Development",
  agency == "NASA" ~ "National Aeronautics and Space Administration",
  agency == "NSF" ~ "National Science Foundation",
  agency == "SSA" ~ "Social Security Administration",
  agency == "Small Business" ~ "Small Business Administration",
  agency == "Transportation" ~ "Department of Transportation",
  agency == "Treasury" ~ "Department of the Treasury",
  agency == "USDA" ~ "Department of Agriculture",
  agency == "Veteran" ~ "Veterans Affairs"
))

```

```{r}


final_repos |>
  na.omit(agency) |>
  mutate(agency = fct_reorder(agency, fork_count, .fun='median')) %>%
  ggplot( aes(x=reorder(agency, fork_count), y=fork_count)) + 
    geom_boxplot() +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  theme_economist() +
  coord_flip() +
  annotation_logticks(sides = 'lr') +
  labs(title = "Distribution of Fork Counts for OSS Projects",
        x = element_blank(),
        y = "Forks") +
  theme(plot.title = element_text(hjust = 22, 
                                face = "bold", 
                                size = 12),
          plot.margin = margin(.2, .2, .2, .2, "cm"),
          legend.title = element_blank(),
          legend.position = "bottom")
  theme(panel.grid.minor = element_blank())
  
ggsave("Revised_13_fork_counts_box.emf", width = 7, height = 4, units = "in")
ggsave("Revised_13_fork_counts_box.pdf", width = 7, height = 4, units = "in")
```

```{r}

final_repos |>
  na.omit(agency) |>
  mutate(agency = fct_reorder(agency, stargazer_count, .fun='median')) %>%
  ggplot( aes(x=reorder(agency, stargazer_count), y=stargazer_count)) + 
    geom_boxplot() +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  theme_economist() +
  coord_flip() +
  annotation_logticks(sides = 'lr') +
  labs(title = "Distribution of Star Counts for OSS Projects",
        x = element_blank(),
        y = "Stars") +
  theme(plot.title = element_text(hjust = 4, 
                                face = "bold", 
                                size = 12),
          plot.margin = margin(.2, .2, .2, .2, "cm"),
          legend.title = element_blank(),
          legend.position = "bottom")
  theme(panel.grid.minor = element_blank())
  
ggsave("Revised_14_star_counts_box.emf", width = 7, height = 4, units = "in")
ggsave("Revised_14_star_counts_box.pdf", width = 7, height = 4, units = "in")
```

### Figure 2

```{r}

# establishing connection and listing all tables in database
con <- dbConnect(MySQL(), user = Sys.getenv("DB_USERNAME"), password = Sys.getenv("DB_PASSWORD"),
    dbname = "codegov", host = "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com")

agency_proj <- dbReadTable(con, "codegov_gh_agency_count")

dbDisconnect(con)

agency_proj <- agency_proj |>
  mutate(
    agency = ifelse(agency == "NASA", "National Aeronautics and Space Administration", agency),
    agency = ifelse(agency == "Deparment of Agriculture", "Department of Agriculture", agency),
    agency = ifelse(agency == "Department of Defence", "Department of Defense", agency),
        agency = ifelse(agency == "Federal Election Commision", "Federal Election Commission", agency),
    agency = ifelse(agency == "Veteran Affairs", "Veterans Affairs", agency)
    
  )
  
  

agency_proj |>
  select(agency, projects) |>
  mutate(agency = fct_reorder(agency, projects)) |>
  ggplot(aes(x = agency, y = projects)) +
    geom_bar(stat = "identity", fill = '#014d64', width=.6) +
    coord_flip() +
  labs(title = "OSS Projects Hosted on GitHub (2009-2021)") +
    labs(x = element_blank(),
      y = "Number of Projects") +
  theme(plot.title = element_text(hjust = 0, 
                                  face = "bold", 
                                  size = 12),
        plot.margin = margin(.2, .5, .2, .2, "cm"))

ggsave("Revised_03_projects_by_agency.emf", width = 7, height = 4, units = "in")
ggsave("Revised_03_projects_by_agency.pdf", width = 7, height = 4, units = "in")
```

### Cost Table

```{r}
# establishing connection and listing all tables in database
con <- dbConnect(MySQL(), user = Sys.getenv("DB_USERNAME"), password = Sys.getenv("DB_PASSWORD"),
    dbname = "codegov", host = "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com")

agency_year_code <- dbReadTable(con, "codegov_gh_commits_by_year_agency")

dbDisconnect(con)
```

```{r, include=FALSE}

#Calculating the Costs

library(data.table)

agency_year_code <- as.data.table(agency_year_code)

#COST BASED ON Additions
agency_year_code[,person_months := round(2.5 * (2.4 * (additions/1000)^1.05)^0.38,5)]

# Formula 1: round(2.5 * (2.4 * (additions/1000)^1.05)^0.38,5)
# Formula 2: round(2.94 * 1.5 *(additions/1000)^1.0997,5)




wage_table <- data.frame(year = c(2009, 2010, 2011, 2012, 2013, 2014,
                                  2015, 2016, 2017, 2018, 2019, 2020, 2021),
                         wages = c(162046,	164134, 168658, 173325, 177136, 182582, 187567, 191632, 195828, 199398, 204159, 210478 , 216786),
                         deflator = c(1.1672463, 1.1513404, 1.1595931, 1.1595495, 1.1462383, 1.1360232, 1.1217853, 1.1100984, 1.0901915, 1.0653788, 1.0469545, 1.0220328, 1))


agency_year_code |> count() # 7751144 repos
agency_year_code |> distinct(agency) %>% count() # 7751144


```

```{r}
investment_pre <- agency_year_code |>
  select(slug, year, agency, person_months, additions) |>
  filter(year > 2008 & year < 2022) |>
  #filter(year == 2021) |>
  left_join(wage_table, by = "year") |>
  mutate(month_wages = (wages / 12),
         investment = (person_months * month_wages)/deflator)# just added

options(scipen=999)


```

```{r}

investment_pre <- investment_pre |>
  mutate(agency = case_when(
  agency == "DOD" ~ "Department of Defense",
  agency == "Department of Energy" ~ "Department of Energy",
  agency == "Department of Homeland Security" ~ "Department of Homeland Security",
  agency == "Department of Justice" ~ "Department of Justice",
  agency == "Department of Labor" ~ "Department of Labor",
  agency == "Education" ~ "Department of Education",
  agency == "Election" ~ "Federal Election Commission",
  agency == "Environmental Protection Agency" ~ "Environmental Protection Agency",
  agency == "GSA" ~ "General Services Administration",
  agency == "HHS" ~ "Department of Health & Human Services",
  agency == "International" ~ "Agency for International Development",
  agency == "NASA" ~ "National Aeronautics and Space Administration",
  agency == "NSF" ~ "National Science Foundation",
  agency == "SSA" ~ "Social Security Administration",
  agency == "Small Business" ~ "Small Business Administration",
  agency == "Transportation" ~ "Department of Transportation",
  agency == "Treasury" ~ "Department of the Treasury",
  agency == "USDA" ~ "Department of Agriculture",
  agency == "Veteran" ~ "Veterans Affairs"
))
```

```{r}
cost_by_agency <- investment_pre |>
  select(agency, year, investment, additions, person_months) |>
  group_by(agency, year) |>
  summarise(total_cost = sum(investment, na.rm = T),
            total_additions = sum(additions, na.rm = T),
            total_pm = sum(person_months, na.rm = T))
```

```{r}

acency_cost_summary <- cost_by_agency |>
  group_by(agency) |>
  summarise(Cost = sum(total_cost),
            Additions = sum(total_additions),
            `Person Months` = sum(total_pm))

write.csv(acency_cost_summary, "Agency_Cost.csv")
```

```{r}


investments_table <- investment_pre |>
  group_by(agency, year) |>
  summarise(projects = n(),
            total_investment = sum(investment),
            total_additions = sum(additions),
            total_pm = sum(person_months)
            )

write.csv(investments_table, "Investment_table.csv")

```
