---
title: "Identify Countries"
author: "Rahul Shrivastava"
date: "2023-07-05"
output: html_document
---

```{r}
library('dplyr')
library('tidyr')
library('RMySQL')
library('countrycode')

```


```{r}

devtools::install_github("brandonleekramer/diverstidy") 
```
#############################################
## Codegov

### Loading in Data from RDS Database

```{r}

# Set up the database connection parameters
db_host <- "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com"
db_port <- 3306
db_name <- "codegov"
db_user <- 
db_password <- 

# Establish the database connection
db <- dbConnect(MySQL(), host = db_host, port = db_port, dbname = db_name, user = db_user, password = db_password)

# Specify the table name you want to pull in
table_name <- "codegov_users_sectors"

# Fetch the entire table into a data frame
query <- paste0("SELECT * FROM ", table_name)
codegov <- dbGetQuery(db, query)

# Close the database connection
dbDisconnect(db)


```

```{r}
library(tidyverse)
library(tidyorgs)
library(diverstidy)

```

### Creating variable for Country using diverstidy package and `detect_geographies` function.

```{r}
codegov <- codegov %>%
  detect_geographies(login, location, "country", email) %>% 
  detect_geographies(login, country, "iso_2")
```

### Pushing to the DBS

```{r}
# Set up the database connection parameters
db_host <- "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com"
db_port <- 3306
db_name <- "codegov"
db_user <- 
db_password <- 

# Establish the database connection
db <- dbConnect(MySQL(), host = db_host, port = db_port, dbname = db_name, user = db_user, password = db_password)

# Push dataframe to database
dbWriteTable(db, name = "codegov_users_sectors", value = codegov, overwrite = TRUE)

# Close the database connection
dbDisconnect(db)

```
#############################################

CRAN

### Loading in Data from RDS Database

```{r}

# Set up the database connection parameters
db_host <- "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com"
db_port <- 3306
db_name <- "cran"
db_user <- 
db_password <- 

# Establish the database connection
db <- dbConnect(MySQL(), host = db_host, port = db_port, dbname = db_name, user = db_user, password = db_password)

# Specify the table name you want to pull in
table_name <- "cran_users_sectors"

# Fetch the entire table into a data frame
query <- paste0("SELECT * FROM ", table_name)
cran <- dbGetQuery(db, query)

# Close the database connection
dbDisconnect(db)


```


### Creating variable for Country using diverstidy package and `detect_geographies` function.

```{r}
cran <- cran %>%
  detect_geographies(login, location, "country", email) %>% 
  detect_geographies(login, country, "iso_2")
```

### Pushing to the DBS

```{r}
# Set up the database connection parameters
db_host <- "oss-1.cij9gk1eehyr.us-east-1.rds.amazonaws.com"
db_port <- 3306
db_name <- "cran"
db_user <- 
db_password <-

# Establish the database connection
db <- dbConnect(MySQL(), host = db_host, port = db_port, dbname = db_name, user = db_user, password = db_password)

# Push dataframe to database
dbWriteTable(db, name = "cran_users_sectors", value = cran, overwrite = TRUE)

# Close the database connection
dbDisconnect(db)

```

